[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[lint]
exclude_lints = [
    "unsafe-typecast",
    "mixed-case-variable",
    "mixed-case-function",
    "screaming-snake-case-immutable",
    "screaming-snake-case-constant",
    "unwrapped-modifier-logic",

]

[invariant]
runs = 128
depth = 128
fail_on_revert = false


fork_url = "${SEPOLIA_RPC_URL}"

etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/your-api-key"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# Add to foundry.toml
